flowchart LR
    A[Business Logic] --> B[Governance]
    B --> C[Tracking Plan]
    C --> D[Case Studies]

    A:::concept
    B:::rules
    C:::implementation
    D:::insights

classDef concept fill:#F0F9FF,stroke:#0369A1,stroke-width:2px,color:#0369A1
classDef rules fill:#FEF9C3,stroke:#A16207,stroke-width:2px,color:#A16207
classDef implementation fill:#F0FDF4,stroke:#15803D,stroke-width:2px,color:#15803D
classDef insights fill:#FFF1F2,stroke:#9F1239,stroke-width:2px,color:#9F1239
